### PR TITLE
Add Certicate authentication from Matthew Powell

### PR DESCRIPTION
**Pull request by essandess**
Add Certicate authentication from Matthew Powell

* Merge code from https://github.com/matthewpowell/pushnotify/blob/master/pushnotify/Net/APNS/SimpleCert.pm
* Suggest version bump to 0.04

cc: @matthewpowell

### CODE REVIEW

**Comment by essandess** [comment]
@rockbone 

We’re all using APNS (still!) and are responding to the upcoming change in Apple’s API: https://developer.apple.com/news/?id=11042019a&1572897862

Matthew Powell has extended your net::APNS::Simple CPAN module to use certificate authentication: https://github.com/matthewpowell/pushnotify/blob/master/pushnotify/Net/APNS/SimpleCert.pm

We could all just fork/hack this code into existing repos, but it would be much better and robust to have this under your version control at CPAN.

Would you be willing to merge in Matthew’s code into a new version of Net::APNS::Simple?

**Comment by rockbone** [comment]
@essandess 

Sorry I didn't notice your message.
I check for fixes and merge.
Thank you.

**Comment by rockbone** [comment]
Though I checked your fixes, there was almost same fixes in other Pull Request #2 .
So I merged it.
But I merged several modifications you fixed manually and wrote your name into META.json as contributor.
I'll upload this version to CPAN in a few days.
Thank you.

**Comment by essandess** [comment]
@rockbone Thanks much!

**Comment by essandess** [comment]
Thank you very much for updating your [Simple.pm](https://metacpan.org/release/Net-APNS-Simple/source/lib/Net/APNS/Simple.pm) CPAN module.

I'm looking at the differences between the updated CPAN version, and the [SimpleCert.pm](https://github.com/matthewpowell/pushnotify/blob/master/pushnotify/Net/APNS/SimpleCert.pm) version from from @matthewpowell that I've added as a [file](https://github.com/macports/macports-ports/pull/8719/files#diff-31bb5c20a209a144d8ccdf928389b1b06b916537d1d2b4e67d6ba2b29381bdb7) `Net/APNS/SimpleCert.pm` in https://github.com/macports/macports-ports/pull/8719. I've verified that this perl [file](https://github.com/macports/macports-ports/pull/8719/files#diff-31bb5c20a209a144d8ccdf928389b1b06b916537d1d2b4e67d6ba2b29381bdb7) `Net/APNS/SimpleCert.pm` works with Apple's new APNS protocol.

I'm honestly a little hesitant to switch over to the CPAN version before understanding the many code differences, but would also like to avoid a fork and base everything on CPAN.

If you don't mind, would you both @rockbone and @matthewpowell please take a look at and comment on these differences?

> `diff -Naur /opt/local/ports/perl/p5-net-apns-simple/work/destroot/opt/local/lib/perl5/vendor_perl/5.28/Net/APNS/Simple.pm /opt/local/lib/pushnotify/Net/APNS/SimpleCert.pm`
```diff
--- /opt/local/ports/perl/p5-net-apns-simple/work/destroot/opt/local/lib/perl5/vendor_perl/5.28/Net/APNS/Simple.pm	2020-10-16 22:49:58.000000000 -0400
+++ /opt/local/lib/pushnotify/Net/APNS/SimpleCert.pm	2020-10-10 09:33:17.000000000 -0400
@@ -1,4 +1,4 @@
-package Net::APNS::Simple;
+package Net::APNS::SimpleCert;
 use 5.008001;
 use strict;
 use warnings;
@@ -9,23 +9,15 @@
 use IO::Select;
 use IO::Socket::SSL qw();
 
-our $VERSION = "0.05";
+our $VERSION = "0.04";
 
-has [qw/auth_key key_id team_id bundle_id development/] => (
+has [qw/cert key development/] => (
     is => 'rw',
 );
 
-has [qw/cert_file key_file passwd_cb/] => (
-    is => 'rw',
-);
-
-has [qw/proxy/] => (
-    is => 'rw',
-    default => $ENV{https_proxy},
-);
-
-has [qw/apns_id apns_expiration apns_collapse_id/] => (
+has apns_expiration => (
     is => 'rw',
+    default => 0,
 );
 
 has apns_priority => (
@@ -37,7 +29,7 @@
 
 sub _host {
     my ($self) = @_;
-    return 'api.' . ($self->development ? 'sandbox.' : '') . 'push.apple.com'
+    return 'api.' . ($self->development ? 'development.' : '') . 'push.apple.com'
 }
 
 sub _port {443}
@@ -45,49 +37,19 @@
 sub _socket {
     my ($self) = @_;
     if (!$self->{_socket} || !$self->{_socket}->opened){
-        my %ssl_opts = (
-             # openssl 1.0.1 support only NPN
-             SSL_npn_protocols => ['h2'],
-             # openssl 1.0.2 also have ALPN
-             SSL_alpn_protocols => ['h2'],
-             SSL_version => 'TLSv1_2',
-        );
-        for (qw/cert_file key_file passwd_cb/) {
-            $ssl_opts{"SSL_$_"} = $self->{$_} if defined $self->{$_};
-        }
-
-        my ($host,$port) = ($self->_host, $self->_port);
-
-        my $socket;
-        if ( my $proxy = $self->proxy ) {
-            $proxy =~ s|^http://|| or die "Invalid proxy $proxy - only http proxy is supported!\n";
-            require Net::HTTP;
-            $socket = Net::HTTP->new(PeerAddr => $proxy) || die $@;
-            $socket->write_request(
-                CONNECT => "$host:$port",
-                Host => "$host:$port",
-                Connection => "Keep-Alive",
-                'Proxy-Connection' => "Keep-Alive",
-            );
-            my ($code, $mess, %h) = $socket->read_response_headers;
-            $code eq '200' or die "Proxy error: $code $mess";
-
-            IO::Socket::SSL->start_SSL(
-                $socket,
-                # explicitly set hostname we should use for SNI
-                SSL_hostname => $host,
-                %ssl_opts,
-            ) or die $! || $IO::Socket::SSL::SSL_ERROR;
-        }
-        else {
-            # TLS transport socket
-            $socket = IO::Socket::SSL->new(
-                PeerHost => $host,
-                PeerPort => $port,
-                %ssl_opts,
-            ) or die $! || $IO::Socket::SSL::SSL_ERROR;
-        }
-        $self->{_socket} = $socket;
+        # TLS transport socket
+        $self->{_socket} = IO::Socket::SSL->new(
+            PeerHost => $self->_host,
+            PeerPort => $self->_port,
+            # openssl 1.0.1 support only NPN
+            SSL_npn_protocols => ['h2'],
+            # openssl 1.0.2 also have ALPN
+            SSL_alpn_protocols => ['h2'],
+            SSL_version => 'TLSv1_2',
+            # for certificate authentication
+            SSL_cert_file => $self->cert,
+            SSL_key_file => $self->key,
+        ) or die $! || $IO::Socket::SSL::SSL_ERROR;
 
         # non blocking
         $self->{_socket}->blocking(0);
@@ -103,44 +65,16 @@
 
 sub prepare {
     my ($self, $device_token, $payload, $cb) = @_;
-    my @headers = (
-        'apns-topic' => $self->bundle_id,
-    );
-
-    for (qw/apns_id apns_priority apns_expiration apns_collapse_id/) {
-        my $v = $self->$_;
-        next unless defined $v;
-        my $k = $_;
-        $k =~ s/_/-/g;
-        push @headers, $k => $v;
-    }
-
-    if ($self->team_id and $self->auth_key and $self->key_id) {
-        require Crypt::PK::ECC;
-        # require for treat pkcs#8 private key
-        Crypt::PK::ECC->VERSION(0.059);
-        require Crypt::JWT;
-        my $claims = {
-            iss => $self->team_id,
-            iat => time,
-        };
-        my $jwt = Crypt::JWT::encode_jwt(
-            payload => $claims,
-            key => [$self->auth_key],
-            alg => $self->algorithm,
-            extra_headers => {
-                kid => $self->key_id,
-            },
-        );
-        push @headers, authorization => sprintf('bearer %s', $jwt);
-    }
-    my $path = sprintf '/3/device/%s', $device_token;
+   my $path = sprintf '/3/device/%s', $device_token;
     push @{$self->{_request}}, {
         ':scheme' => 'https',
         ':authority' => join(":", $self->_host, $self->_port),
         ':path' => $path,
         ':method' => 'POST',
-        headers => \@headers,
+        headers => [
+            'apns-expiration' => $self->apns_expiration,
+            'apns-priority' => $self->apns_priority,
+        ],
         data => JSON::encode_json($payload),
         on_done => $cb,
     };
@@ -192,7 +126,7 @@
 
 =head1 NAME
 
-Net::APNS::Simple - APNS Perl implementation
+Net::APNS::SimpleCert - APNS Perl implementation
 
 =head1 DESCRIPTION
 
@@ -203,26 +137,15 @@
 
 =head1 SYNOPSIS
 
-    use Net::APNS::Simple;
+    use Net::APNS::SimpleCert;
 
-    # With provider authentication tokens
-    my $apns = Net::APNS::Simple->new(
+    my $apns = Net::APNS::SimpleCert->new(
         # enable if development
         # development => 1,
-        auth_key => '/path/to/auth_key.p8',
-        key_id => 'AUTH_KEY_ID',
-        team_id => 'APP_PREFIX',
-        bundle_id => 'APP_ID',
-    );
-
-    # With SSL certificates
-    my $apns = Net::APNS::Simple->new(
-        # enable if development
-        # development => 1,
-        cert_file => '/path/to/cert.pem',
-        key_file => '/path/to/key.pem',
-        passwd_cb => sub { return 'key-password' },
-        bundle_id => 'APP_ID',
+        cert => '/path/to/certificate.pem',
+        key => '/path/to/key.pem',
+        apns_expiration => 0,
+        apns_priority => 10,
     );
 
     # 1st request
@@ -262,57 +185,29 @@
 
 =head1 METHODS
 
-=head2 my $apns = Net::APNS::Simple->new(%arg)
+=head2 my $apns = Net::APNS::SimpleCert->new(%arg)
 
 =over
 
 =item development : bool
 
-Switch API's URL to 'api.sandbox.push.apple.com' if enabled.
-
-=item auth_key : string
-
-Private key file for APNS obtained from Apple.
-
-=item team_id : string
-
-Team ID (App Prefix)
-
-=item bundle_id : string
-
-Bundle ID (App ID)
+Switch API's URL to 'api.development.push.apple.com' if enabled.
 
-=item cert_file : string
+=item cert : string
 
-SSL certificate file.
+Path to Apple push notification certificate.
 
-=item key_file : string
+=item key : string
 
-SSL key file.
-
-=item passwd_cb : sub reference
-
-If the private key is encrypted, this should be a reference to a subroutine that should return the password required to decrypt your private key.
-
-=item apns_id : string
-
-Canonical UUID that identifies the notification (apns-id header).
+Path to Apple push notification certificate's private key.
 
 =item apns_expiration : number
 
-Sets the apns-expiration header.
+Default 0.
 
 =item apns_priority : number
 
-Sets the apns-priority header. Default 10.
-
-=item apns_collapse_id : string
-
-Sets the apns-collapse-id header.
-
-=item proxy : string
-
-URL of a proxy server. Default $ENV{https_proxy}. Pass undef to disable proxy.
+Default 10.
 
 =back
 
@@ -334,7 +229,7 @@
 
 =head1 LICENSE
 
-Copyright (C) Tooru Tsurukawa.
+Based on Net::APNS::Simple, Copyright (C) Tooru Tsurukawa.
 
 This library is free software; you can redistribute it and/or modify
 it under the same terms as Perl itself.
@@ -342,6 +237,9 @@
 =head1 AUTHOR
 
 Tooru Tsurukawa E<lt>rockbone.g at gmail.comE<gt>
+Modifications by Matthew Powell E<lt>matthew at atom.netE<gt>
+
+https://github.com/rockbone/p5-Net-APNS-Simple
 
 =cut
```

**Pull request closed without merging**
